-- =============================================================
-- IGSAVEGO · Seed the 6 default guide articles
-- Run AFTER supabase/guides.sql in SQL Editor. Safe to re-run
-- (on conflict do nothing).
-- =============================================================

insert into public.guide_articles
  (id, slug, lang, keyword, tool, title, meta_description, h1, excerpt, sections, faqs, related_slugs, enabled)
values
  ('gd-ar-reels-iphone','تحميل-ريلز-انستقرام-للايفون-بدون-برامج','ar','تحميل ريلز انستقرام للايفون','reels',
   'تحميل ريلز انستقرام للايفون بدون برامج (2026) - خطوة بخطوة',
   'شرح تحميل ريلز انستقرام للايفون بدون برامج: انسخ الرابط من التطبيق، الصقه في IGSAVEGO، واحفظ الريل بجودة HD في صورك مباشرة.',
   'تحميل ريلز انستقرام للايفون بدون برامج',
   'دليل سريع لحفظ أي ريل على الايفون (Safari) بدون تثبيت تطبيقات: نسخ، لصق، تحميل.',
   '[{"heading":"1. انسخ رابط الريل من تطبيق انستقرام","body":"افتح الريل في تطبيق انستقرام على الايفون، اضغط زر المشاركة (السهم) ثم اختر \\"نسخ الرابط\\". تأكد أن الحساب عام لأن الريلز الخاصة لا يمكن تحميلها."},{"heading":"2. الصق الرابط في متصفح Safari","body":"افتح موقع IGSAVEGO في Safari والصق الرابط في مربع البحث ثم اضغط زر التحميل. ستظهر معاينة الريل مع زر حفظ بجودة 1080p خلال ثوانٍ."},{"heading":"3. احفظ الريل في تطبيق الصور","body":"اضغط \\"تحميل\\"، وعند انتهاء التنزيل اختر \\"حفظ في الصور\\" من قائمة المشاركة. ستجد الريل في ألبوم الكاميرا بجودته الأصلية وبدون علامة مائية."}]'::jsonb,
   '[{"question":"هل أحتاج تطبيقاً لتحميل ريلز انستقرام على الايفون؟","answer":"لا. متصفح Safari مع موقع IGSAVEGO يكفي تماماً: نسخ الرابط ثم لصقه ثم التحميل، بدون تثبيت أي شيء."},{"question":"أين يُحفظ الريل بعد التحميل على الايفون؟","answer":"يُنزّل الملف أولاً إلى تطبيق \\"الملفات\\"، ومن قائمة المشاركة اختر \\"حفظ الفيديو\\" لينتقل إلى مكتبة الصور."},{"question":"هل تحميل الريلز بهذه الطريقة آمن للحساب؟","answer":"نعم، لا تدخل أي بيانات ولا تسجل الدخول. التحميل مجهول تماماً ولا يصل أي إشعار لصاحب الريل."}]'::jsonb,
   array['حفظ-ستوري-انستقرام-بدون-ما-يدري','تحميل-فيديو-انستا-للاندرويد-بجودة-عالية'],
   true),
  ('gd-ar-story-anon','حفظ-ستوري-انستقرام-بدون-ما-يدري','ar','حفظ ستوري انستقرام بدون ما يدري','story',
   'حفظ ستوري انستقرام بدون ما يدري صاحبها (مجهول 100%)',
   'طريقة حفظ ستوري انستقرام بدون ما يدري صاحب الحساب: أدخل اسم المستخدم، حمّل الستوري صوراً وفيديو بجودة عالية وبشكل مجهول تماماً.',
   'حفظ ستوري انستقرام بدون ما يدري',
   'احفظ أي ستوري عام بدون ظهور اسمك في قائمة المشاهدين: أدخل اليوزر وحمّل مباشرة.',
   '[{"heading":"لماذا لا يظهر اسمك؟","body":"عند التحميل عبر IGSAVEGO لا تفتح الستوري من حسابك أصلاً. السيرفر يجلب نسخة عامة من ملفات انستقرام، فلا تُسجَّل مشاهدة باسمك أبداً ولا يصل أي إشعار لصاحب الحساب."},{"heading":"خطوات حفظ الستوري","body":"اختر تبويب Story من الأعلى، اكتب اسم المستخدم (username) بدون @، ثم اضغط تحميل. ستظهر الستوريات النشطة للحساب العام مع أزرار حفظ للصور والفيديو."},{"heading":"شروط مهمة","body":"الطريقة تعمل فقط مع الحسابات العامة. الحسابات الخاصة والستوريات المنتهية (بعد 24 ساعة) لا يمكن الوصول إليها احتراماً للخصوصية."}]'::jsonb,
   '[{"question":"هل يعرف صاحب الحساب أني حفظت الستوري؟","answer":"لا. لا تظهر في قائمة المشاهدين ولا يصله أي تنبيه، لأن المشاهدة لا تتم من حسابك."},{"question":"هل يمكن حفظ ستوري حساب خاص؟","answer":"لا، وهذه حماية مقصودة للخصوصية. الأداة تدعم الحسابات العامة فقط."},{"question":"بأي صيغة تُحفظ الستوري؟","answer":"الصور بصيغة JPG والفيديو بصيغة MP4 بجودة تصل إلى 1080p."}]'::jsonb,
   array['تحميل-ريلز-انستقرام-للايفون-بدون-برامج','تحميل-فيديو-انستا-للاندرويد-بجودة-عالية'],
   true),
  ('gd-ar-android-video','تحميل-فيديو-انستا-للاندرويد-بجودة-عالية','ar','تحميل فيديو انستا للاندرويد','video',
   'تحميل فيديو انستا للاندرويد بجودة عالية MP4 (شرح مصور)',
   'شرح تحميل فيديو انستا للاندرويد بجودة 1080p: انسخ رابط الفيديو من التطبيق، الصقه في IGSAVEGO بمتصفح كروم، واحفظه في مجلد التنزيلات.',
   'تحميل فيديو انستا للاندرويد بجودة عالية',
   'احفظ أي فيديو عام على هاتفك الأندرويد بمتصفح كروم فقط: نسخ، لصق، تحميل MP4.',
   '[{"heading":"1. نسخ رابط الفيديو","body":"من تطبيق انستقرام افتح الفيديو، اضغط النقاط الثلاث أو زر المشاركة ثم \\"نسخ الرابط\\". يعمل هذا مع المنشورات والريلز على حد سواء."},{"heading":"2. التحميل من متصفح كروم","body":"افتح IGSAVEGO في كروم والصق الرابط ثم اضغط تحميل. اختر جودة 1080p Full HD وسيبدأ التنزيل فوراً إلى مجلد Downloads في هاتفك."},{"heading":"3. تشغيل الفيديو بدون إنترنت","body":"بعد اكتمال التحميل شغّل الملف بأي مشغّل فيديو. الملف بصيغة MP4 القياسية يعمل على كل الأجهزة ويمكن مشاركته عبر واتساب وتليجرام."}]'::jsonb,
   '[{"question":"أين أجد الفيديو بعد تحميله على الأندرويد؟","answer":"في مجلد \\"التنزيلات\\" (Downloads) أو في تطبيق \\"ملفاتي\\"، ويمكنك نقله إلى الاستوديو."},{"question":"هل يوجد حد لعدد الفيديوهات؟","answer":"لا، التحميل غير محدود ومجاني بالكامل بدون حساب أو اشتراك."},{"question":"لماذا يظهر الفيديو أحياناً كصورة؟","answer":"بعض المنشورات لا يعرض إنستقرام لها رابط فيديو علناً، فيظهر الغلاف فقط. جرّب رابطاً آخر أو أعد المحاولة لاحقاً."}]'::jsonb,
   array['تحميل-ريلز-انستقرام-للايفون-بدون-برامج','حفظ-ستوري-انستقرام-بدون-ما-يدري'],
   true),
  ('gd-en-reels-iphone','download-instagram-reels-on-iphone-without-app','en','download instagram reels on iPhone','reels',
   'How to Download Instagram Reels on iPhone Without an App (2026)',
   'Download Instagram Reels on iPhone without any app: copy the reel link, paste it into IGSAVEGO in Safari, and save it in HD to your Photos.',
   'Download Instagram Reels on iPhone Without an App',
   'Save any public reel on iPhone with Safari only: copy, paste, download in 1080p.',
   '[{"heading":"1. Copy the reel link","body":"Open the reel in the Instagram app, tap Share, then \\"Copy Link\\". The account must be public — private reels cannot be downloaded."},{"heading":"2. Paste it in Safari","body":"Open IGSAVEGO in Safari, paste the link into the search box and hit Download. A preview appears within seconds with an HD save button."},{"heading":"3. Save to Photos","body":"Tap Download, then use the share sheet to \\"Save Video\\". The reel lands in your camera roll in original quality with no watermark."}]'::jsonb,
   '[{"question":"Do I need an app to download reels on iPhone?","answer":"No. Safari plus IGSAVEGO is enough — no installs, no sign-ups, no watermarks."},{"question":"Where do downloaded reels go on iPhone?","answer":"First to the Files app, then move them to Photos via the share sheet \\"Save Video\\" option."},{"question":"Is it anonymous?","answer":"Yes. No login is required and the reel owner is never notified."}]'::jsonb,
   array['save-instagram-story-anonymously','download-instagram-photos-to-android-gallery'],
   true),
  ('gd-en-story-anon','save-instagram-story-anonymously','en','save instagram story anonymously','story',
   'How to Save an Instagram Story Anonymously (Viewer List Free)',
   'Save Instagram Stories anonymously without appearing on the viewer list: enter the username in IGSAVEGO and download story photos and videos in HD.',
   'Save Instagram Story Anonymously',
   'Download any public story without your name on the viewer list: just the username.',
   '[{"heading":"Why you stay invisible","body":"You never open the story from your account. Our server fetches a public copy of the media files, so no view is registered under your name and the owner gets no notification."},{"heading":"Steps to save a story","body":"Switch to the Story tab, type the username without @, and hit download. Active stories of public accounts appear with save buttons for photos (JPG) and videos (MP4)."},{"heading":"Limitations","body":"Only public accounts work. Private accounts and stories older than 24 hours are inaccessible by design, to respect privacy."}]'::jsonb,
   '[{"question":"Will they know I saved their story?","answer":"No. You never appear on the viewer list and no notification is sent."},{"question":"Can I save stories from private accounts?","answer":"No — only public accounts are supported, as a deliberate privacy protection."},{"question":"What format are saved stories?","answer":"Photos as JPG and videos as MP4 in up to 1080p quality."}]'::jsonb,
   array['download-instagram-reels-on-iphone-without-app','download-instagram-photos-to-android-gallery'],
   true),
  ('gd-en-photo-android','download-instagram-photos-to-android-gallery','en','download instagram photos to gallery','photo',
   'How to Download Instagram Photos to Your Android Gallery (HD)',
   'Download Instagram photos to your Android gallery in original HD quality: copy the post link, paste it into IGSAVEGO in Chrome, and save the JPG.',
   'Download Instagram Photos to Android Gallery',
   'Save any public photo or carousel to your Android phone with Chrome only.',
   '[{"heading":"1. Copy the photo link","body":"Open the post in Instagram, tap the three dots or Share, then \\"Copy Link\\". Works for single photos and multi-slide carousels."},{"heading":"2. Download in Chrome","body":"Paste the link into IGSAVEGO, hit Download, and save each slide in original resolution JPG. Carousels are detected automatically with per-slide buttons."},{"heading":"3. Find it in your gallery","body":"Files land in the Downloads folder. Move them to your gallery or DCIM folder, or open them directly with any gallery app."}]'::jsonb,
   '[{"question":"Can I download all carousel slides?","answer":"Yes. Carousels are detected with individual HD download buttons per slide."},{"question":"What quality are the photos?","answer":"Original uploaded resolution in JPG, typically 1080px and up."},{"question":"Is there a download limit?","answer":"No limits — free and unlimited without an account."}]'::jsonb,
   array['download-instagram-reels-on-iphone-without-app','save-instagram-story-anonymously'],
   true)
on conflict (id) do nothing;
